### ISSUE TITLE
is BOM obsolete?

### ISSUE THREAD

**Issue by afeezaziz** [openpowerquality/opqbox2#34]
I have been trying to find the BOM for the project in the repo but the only BOM.txt in this repo has a note "obsolete". Is there an updated version somewhere?

**Comment by philipmjohnson** [comment]
Checking on this, will have information soon....

**Comment by sergey-negrashov** [comment]
Hello,
  I am sorry it took me so long to get back to you. I am going through some medical issues, which kept me from using my computer. I am now mostly in one piece and the development is ongoing.
 We are currently in the design phase for OPQBox2.6 so the BOM has been changing on the weekly basis. At a certain  point i gave up on updating it with every part change. I intend to post it once the layout and Gerber are finished. I expect it to be up in a couple of weeks.
  If you are looking for a hardware proven design I suggest you take a look at opqbox1, since we had success in deploying them. Opqbox2 will be better in almost every way, but I don't expect all the bugs to be worked out until we manufacture and test a few of them.
  I will leave the issue open as a reminder to post the BOM.

**Comment by sergey-negrashov** [comment]
BOM is now current
